//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurCSharp.OurForm.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
        "Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance =
            ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default { get { return defaultInstance; } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnNrmlDrwCrcl { get { return ((bool)(this["ClsBttnNrmlDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnNrmlDrwCrclBrdr { get { return ((bool)(this["ClsBttnNrmlDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClsBttnNrmlDrwBx { get { return ((bool)(this["ClsBttnNrmlDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClsBttnNrmlDrwBxBrdr { get { return ((bool)(this["ClsBttnNrmlDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ClsBttnNrmlCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnNrmlCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnNrmlCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnNrmlCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ClsBttnNrmlBxClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnNrmlBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnNrmlBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnNrmlBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnHvrdDrwCrcl { get { return ((bool)(this["ClsBttnHvrdDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnHvrdDrwCrclBrdr { get { return ((bool)(this["ClsBttnHvrdDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnHvrdDrwBx { get { return ((bool)(this["ClsBttnHvrdDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnHvrdDrwBxBrdr { get { return ((bool)(this["ClsBttnHvrdDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 0, 0")]
        public global::System.Drawing.Color ClsBttnHvrdCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnHvrdCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnHvrdCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnHvrdCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 0, 0")]
        public global::System.Drawing.Color ClsBttnHvrdBxClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnHvrdBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnHvrdBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnHvrdBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnClckdDrwCrcl { get { return ((bool)(this["ClsBttnClckdDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnClckdDrwCrclBrdr { get { return ((bool)(this["ClsBttnClckdDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnClckdDrwBx { get { return ((bool)(this["ClsBttnClckdDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnClckdDrwBxBrdr { get { return ((bool)(this["ClsBttnClckdDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 0, 0")]
        public global::System.Drawing.Color ClsBttnClckdCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnClckdCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnClckdCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnClckdCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 0, 0")]
        public global::System.Drawing.Color ClsBttnClckdBxClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnClckdBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnClckdBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnClckdBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnDsbldDrwCrcl { get { return ((bool)(this["ClsBttnDsbldDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnDsbldDrwCrclBrdr { get { return ((bool)(this["ClsBttnDsbldDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnDsbldDrwBx { get { return ((bool)(this["ClsBttnDsbldDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClsBttnDsbldDrwBxBrdr { get { return ((bool)(this["ClsBttnDsbldDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 0, 0")]
        public global::System.Drawing.Color ClsBttnDsbldCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnDsbldCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnDsbldCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnDsbldCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 0, 0")]
        public global::System.Drawing.Color ClsBttnDsbldBxClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnDsbldBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color ClsBttnDsbldBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["ClsBttnDsbldBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnNrmlDrwCrcl { get { return ((bool)(this["MxmzBttnNrmlDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnNrmlDrwCrclBrdr { get { return ((bool)(this["MxmzBttnNrmlDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MxmzBttnNrmlDrwBx { get { return ((bool)(this["MxmzBttnNrmlDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MxmzBttnNrmlDrwBxBrdr { get { return ((bool)(this["MxmzBttnNrmlDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MxmzBttnNrmlCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnNrmlCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnNrmlCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnNrmlCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MxmzBttnNrmlBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnNrmlBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnNrmlBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnNrmlBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnHvrdDrwCrcl { get { return ((bool)(this["MxmzBttnHvrdDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnHvrdDrwCrclBrdr { get { return ((bool)(this["MxmzBttnHvrdDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnHvrdDrwBx { get { return ((bool)(this["MxmzBttnHvrdDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnHvrdDrwBxBrdr { get { return ((bool)(this["MxmzBttnHvrdDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150, 150")]
        public global::System.Drawing.Color MxmzBttnHvrdCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnHvrdCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnHvrdCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnHvrdCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150, 150")]
        public global::System.Drawing.Color MxmzBttnHvrdBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnHvrdBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnHvrdBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnHvrdBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnClckdDrwCrcl { get { return ((bool)(this["MxmzBttnClckdDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnClckdDrwCrclBrdr { get { return ((bool)(this["MxmzBttnClckdDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnClckdDrwBx { get { return ((bool)(this["MxmzBttnClckdDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnClckdDrwBxBrdr { get { return ((bool)(this["MxmzBttnClckdDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MxmzBttnClckdCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnClckdCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnClckdCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnClckdCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MxmzBttnClckdBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnClckdBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnClckdBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnClckdBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnDsbldDrwCrcl { get { return ((bool)(this["MxmzBttnDsbldDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnDsbldDrwCrclBrdr { get { return ((bool)(this["MxmzBttnDsbldDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnDsbldDrwBx { get { return ((bool)(this["MxmzBttnDsbldDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MxmzBttnDsbldDrwBxBrdr { get { return ((bool)(this["MxmzBttnDsbldDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MxmzBttnDsbldCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnDsbldCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnDsbldCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnDsbldCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MxmzBttnDsbldBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnDsbldBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MxmzBttnDsbldBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MxmzBttnDsbldBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnNrmlDrwCrcl { get { return ((bool)(this["MnmzBttnNrmlDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnNrmlDrwCrclBrdr { get { return ((bool)(this["MnmzBttnNrmlDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MnmzBttnNrmlDrwBx { get { return ((bool)(this["MnmzBttnNrmlDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MnmzBttnNrmlDrwBxBrdr { get { return ((bool)(this["MnmzBttnNrmlDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MnmzBttnNrmlCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnNrmlCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnNrmlCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnNrmlCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MnmzBttnNrmlBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnNrmlBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnNrmlBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnNrmlBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnHvrdDrwCrcl { get { return ((bool)(this["MnmzBttnHvrdDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnHvrdDrwCrclBrdr { get { return ((bool)(this["MnmzBttnHvrdDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnHvrdDrwBx { get { return ((bool)(this["MnmzBttnHvrdDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnHvrdDrwBxBrdr { get { return ((bool)(this["MnmzBttnHvrdDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150, 150")]
        public global::System.Drawing.Color MnmzBttnHvrdCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnHvrdCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnHvrdCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnHvrdCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150, 150")]
        public global::System.Drawing.Color MnmzBttnHvrdBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnHvrdBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnHvrdBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnHvrdBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnClckdDrwCrcl { get { return ((bool)(this["MnmzBttnClckdDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnClckdDrwCrclBrdr { get { return ((bool)(this["MnmzBttnClckdDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnClckdDrwBx { get { return ((bool)(this["MnmzBttnClckdDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnClckdDrwBxBrdr { get { return ((bool)(this["MnmzBttnClckdDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MnmzBttnClckdCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnClckdCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnClckdCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnClckdCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MnmzBttnClckdBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnClckdBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnClckdBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnClckdBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnDsbldDrwCrcl { get { return ((bool)(this["MnmzBttnDsbldDrwCrcl"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnDsbldDrwCrclBrdr { get { return ((bool)(this["MnmzBttnDsbldDrwCrclBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnDsbldDrwBx { get { return ((bool)(this["MnmzBttnDsbldDrwBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MnmzBttnDsbldDrwBxBrdr { get { return ((bool)(this["MnmzBttnDsbldDrwBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MnmzBttnDsbldCrclClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnDsbldCrclClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnDsbldCrclBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnDsbldCrclBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color MnmzBttnDsbldBxClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnDsbldBxClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color MnmzBttnDsbldBxBrdrClr
        {
            get { return ((global::System.Drawing.Color)(this["MnmzBttnDsbldBxBrdrClr"])); }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public string ClsBrnNrmlCrclBrdrClr { get { return ((string)(this["ClsBrnNrmlCrclBrdrClr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ClsBttnNrmlDrBx { get { return ((string)(this["ClsBttnNrmlDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ClsBttnNrmlDrBxBrdr { get { return ((string)(this["ClsBttnNrmlDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ClsBttnHvrdDrBx { get { return ((string)(this["ClsBttnHvrdDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ClsBttnHvrdDrBxBrdr { get { return ((string)(this["ClsBttnHvrdDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ClsBttnClckdDrBx { get { return ((string)(this["ClsBttnClckdDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ClsBttnClckdDrBxBrdr { get { return ((string)(this["ClsBttnClckdDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ClsBttnDsbldDrBx { get { return ((string)(this["ClsBttnDsbldDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ClsBttnDsbldDrBxBrdr { get { return ((string)(this["ClsBttnDsbldDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string MxmzBttnNrmlDrBx { get { return ((string)(this["MxmzBttnNrmlDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string MxmzBttnNrmlDrBxBrdr { get { return ((string)(this["MxmzBttnNrmlDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MxmzBttnHvrdDrBx { get { return ((string)(this["MxmzBttnHvrdDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MxmzBttnHvrdDrBxBrdr { get { return ((string)(this["MxmzBttnHvrdDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MxmzBttnClckdDrBx { get { return ((string)(this["MxmzBttnClckdDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MxmzBttnClckdDrBxBrdr { get { return ((string)(this["MxmzBttnClckdDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MxmzBttnDsbldDrBx { get { return ((string)(this["MxmzBttnDsbldDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MxmzBttnDsbldDrBxBrdr { get { return ((string)(this["MxmzBttnDsbldDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string MnmzBttnNrmlDrBx { get { return ((string)(this["MnmzBttnNrmlDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string MnmzBttnNrmlDrBxBrdr { get { return ((string)(this["MnmzBttnNrmlDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MnmzBttnHvrdDrBx { get { return ((string)(this["MnmzBttnHvrdDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MnmzBttnHvrdDrBxBrdr { get { return ((string)(this["MnmzBttnHvrdDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MnmzBttnClckdDrBx { get { return ((string)(this["MnmzBttnClckdDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MnmzBttnClckdDrBxBrdr { get { return ((string)(this["MnmzBttnClckdDrBxBrdr"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MnmzBttnDsbldDrBx { get { return ((string)(this["MnmzBttnDsbldDrBx"])); } }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string MnmzBttnDsbldDrBxBrdr { get { return ((string)(this["MnmzBttnDsbldDrBxBrdr"])); } }
    }
}
